server {
    listen 80;
    listen [::]:80;
    server_name apitool.gwk.web.id;

    root /home/kuyaba/qris-tool;
    index index.html;

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 30d;
        add_header Cache-Control "public";
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
